In [1]:
import sys
import numpy as np
import sacc
import yaml
sys.path.insert(1, '/home/jaimerz/Documents/UCL/pacc')
import pacc

In [2]:
s = sacc.Sacc.load_fits("/home/jaimerz/Documents/UCL/3x2_analytical/data/HSC/HSC.sacc")
y = yaml.load(open("/home/jaimerz/Documents/UCL/3x2_analytical/data/HSC/HSC.yml"), Loader=yaml.FullLoader)

In [15]:
cle = pacc.ClsEnsemble(s,y)

In [12]:
errs = np.sqrt(np.diag(cle.cov))

In [14]:
seg_errs = [errs[ind] for ind in cle.indices]
seg_errs

[array([9.52513486e-07]),
 array([5.79867854e-07, 2.26221485e-07, 1.10280282e-07, 3.65058402e-08,
        2.01316062e-08, 1.33101128e-08, 5.75607984e-09, 3.62345932e-09,
        2.43794702e-09]),
 array([7.09655389e-07, 2.80245384e-07, 1.34893730e-07]),
 array([4.91887870e-07, 1.97189551e-07, 9.71335864e-08, 3.18927869e-08,
        1.71849722e-08, 1.11391315e-08, 4.74039860e-09, 2.96223980e-09,
        2.00328384e-09]),
 array([4.25070540e-07, 1.72288914e-07, 8.35765656e-08, 2.65687554e-08,
        1.38359182e-08, 8.82820039e-09, 3.74882376e-09, 2.37130179e-09,
        1.63529822e-09]),
 array([5.10636145e-07, 2.12753663e-07, 1.04287913e-07, 3.30730621e-08]),
 array([3.07329055e-07, 1.27834814e-07, 6.47753312e-08, 2.14151581e-08,
        1.16040593e-08, 7.53238738e-09, 3.21831773e-09, 2.03638796e-09,
        1.40682530e-09]),
 array([2.65619970e-07, 1.11722618e-07, 5.57279390e-08, 1.78381276e-08,
        9.34211968e-09, 5.96945066e-09, 2.54488653e-09, 1.63002574e-09,
        1.14838505

In [4]:
cle.indices

[array([0]),
 array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([10, 11, 12]),
 array([13, 14, 15, 16, 17, 18, 19, 20, 21]),
 array([22, 23, 24, 25, 26, 27, 28, 29, 30]),
 array([31, 32, 33, 34]),
 array([35, 36, 37, 38, 39, 40, 41, 42, 43]),
 array([44, 45, 46, 47, 48, 49, 50, 51, 52]),
 array([53, 54, 55, 56, 57, 58, 59, 60, 61]),
 array([62, 63, 64, 65]),
 array([210]),
 array([211, 212, 213]),
 array([214, 215, 216, 217]),
 array([218, 219, 220, 221]),
 array([222]),
 array([223, 224, 225]),
 array([226, 227, 228, 229]),
 array([230, 231, 232, 233]),
 array([234]),
 array([235, 236, 237]),
 array([238, 239, 240, 241]),
 array([242, 243, 244, 245]),
 array([246]),
 array([247, 248, 249]),
 array([250, 251, 252, 253]),
 array([254, 255, 256, 257]),
 array([528, 529, 530, 531, 532, 533]),
 array([534, 535, 536, 537, 538, 539]),
 array([540, 541, 542, 543, 544, 545]),
 array([546, 547, 548, 549, 550, 551]),
 array([552, 553, 554, 555, 556, 557]),
 array([558, 559, 560, 561, 562, 563]),
 array

In [ ]:
pacc.plot_cls([cle], [['lens_0', 'lens_0'],
              ['lens_1', 'lens_1'],
              ['lens_2', 'lens_2'], 
              ['lens_3', 'lens_3']])

In [ ]:
pacc.plot_cls([cle, cle], cle.pairs[:10])

In [ ]:
import matplotlib.pyplot as plt
plt.rcParams['xtick.labelsize'] = 12
plt.rcParams['ytick.labelsize'] = 12
plt.rcParams['axes.labelsize'] = 12

In [ ]:
wanted_pairs = [['lens_0', 'lens_0'],
              ['lens_1', 'lens_1'],
              ['lens_2', 'lens_2'], 
              ['lens_3', 'lens_3']]

In [ ]:
proposed_covs = []
for i, pair1 in enumerate(wanted_pairs):
    for j, pair2 in enumerate(wanted_pairs):
        cov = []
        cov.append(pair1)
        cov.append(pair2)
        proposed_covs.append(cov)
proposed_covs

In [ ]:
cle.indices

In [ ]:
t1 = np.transpose(cle.pairs)[0]
t2 = np.transpose(cle.pairs)[1]

In [ ]:
len(cle.pairs)

In [ ]:
ps = [cle.pairs.index(pair) for pair in cle.pairs]
cle.edges[ps]

In [ ]:
cl_names = []
for pair in cle.pairs:
    cl_names.append(pair[0] + ' x ' + pair[1])
cl_names

In [ ]:

plt.figure(figsize = (20,20))
plt.imshow(np.log10(np.abs(cle.cov)))
plt.xticks(cle.edges[:-1], cl_names, rotation=90)
plt.yticks(cle.edges[:-1], cl_names)
plt.show()

In [ ]:
cle.edges

In [ ]:
pl